index.js
#12 
It's all fraction symbols Unicode supports, except `↉`.
=> add fraction symbols

makefile.js, package.json, readme.md
Added a `makefile.js` script that retrieves the figures from the module and adds them to the readme. The script also executes on `prepublish` to make sure it is executed before released to `npm`.
If you rather give it another name, suggestions are welcome :).
=> add list of figures in readme - fixes #17

index.js, readme.md
The `bullet` figure `U-25cf` `●` displays correctly on Windows, is there a reason to use `*` instead?
=> Improve `bullet` figure

index.js
Background at https://github.com/sindresorhus/figures/pull/36#discussion_r600462609
This uses `main.*` to make it clearer that the Windows and non-Windows variants of the `line` figure are the same Unicode codepoint.
=> Use `main.line` instead of repeating character

index.js, readme.md
The `pointerSmall` figure `U-203a` `›` displays correctly on Windows, is there a reason to use `U-00bb` `»` instead?
Note: the `pointer` figure `U-276f` `❯` does not display correctly, and the best replacement seems to be ASCII `>` (currently used). However, the difference of size with `pointerSmall` seems good enough in both cases.
=> Improve `pointerSmall` figure

index.js, readme.md, test.js
This improves the `star` figure on Windows CP850 by using `U-2736` `✶` instead of ASCII `*`.
=> Improve the `star` figure

index.js, readme.md
The `dot` figure `U-2024` `․` displays correctly on Windows, is there a reason to use the ASCII dot `.` instead?
=> Improve `dot` figure

index.js, readme.md
The `ellipsis` figure `U-2026` `…` displays correctly on Windows, is there a reason to use the ASCII dots `...` instead?
=> Improve `ellipsis` figure

test.js
This adds a test validating that figures are defined, are strings and are non-empty.
The opposite could happen on typos for example.
=> Add a test validating figures are non-empty strings

index.js
e97270a8858dd824135962db5b7d940b00a94a41 added both `circleQuestionMark` and `questionMarkPrefix`, with the same Unicode codepoints.
It added a fallback for `questionMarkPrefix` on Linux to not looking good on Ubuntu. However, it seems like this should apply to `circleQuestionMark` as well.
This is how this looks like before this fix on Ubuntu 20.10 (Gnome terminal):
After this fix, both characters are the same as the left one.
=> Fix `circleQuestionMark` character does not display properly on Ubuntu

index.js
This PR improves the performance of the main function by memoizing part of it.
If you'd prefer to use a memoization library, please let me know which one to use, and I will add it :+1:
=> Improve performance of main function

readme.md
Since the symbols are meant to be displayed in a terminal, not in a browser, it probably would make sense to use code ticks around them in the `readme.md`. It will display them in a way that's closer to the final user experience. For example, it looks like the `triangleLeft` has colors while `triangleDown` does not, even though they look very similar in a terminal.
An alternative would be to wrap the whole table inside triple-ticks. Please let me know which solution sounds better.
=> Use code ticks around symbols in `readme.md`

index.js, readme.md, test.js
Part of #57.
This fixes the `square` character so it fills the whole block in both Windows and Unix. Previously, on Unix, the character had a 1/8 top margin. 
I would personally consider this a breaking change since some consumers might depend on that margin being present, e.g. if they want to separate a progress bar with the previous or next row.
I will follow up with another PR to add more fill characters for this type of use cases (e.g. progress bars).
=> Fix `square` character to fill the whole area

readme.md
Fixes #60.
There are several ways to fix the issue described in #60.
In this PR, the identical figures are omitted in the Windows column. Other approaches could have been:
- Using merged rows, which would require using HTML
- Using a triple-tick code block for the whole table
- Using "same" or some punctuation sign in the Windows column
Please let me know what you think.
=> Do not show identical figures in `readme.md`

index.d.ts, index.js, index.test-d.ts, readme.md, test.js
This PR addresses part of #50.
This separates the main function to a named export instead of merged to the main/default export.
In two follow-up PRs, I will also:
- Drop Node.js <12 support
- Move from CommonJS to ES modules. When doing so, this module will have both a default export and several named exports (`replaceSymbols()`, `main` and `windows`).
=> Separate `replaceSymbols()` method

index.d.ts, index.js, index.test-d.ts, readme.md, test.js
Based on https://github.com/sindresorhus/figures/pull/77#issuecomment-871919015
This renames `main` and `windows` exports to `mainSymbols` and `windowsSymbols`.
=> Rename `main` and `windows` to `mainSymbols` and `windowsSymbols`

.github/workflows/main.yml, package.json
This drops support for Node <12, as part of #50.
=> Drop support for Node <12

index.js, package.json, test.js
This adds support for Windows terminals which support Unicode fonts using [`is-unicode-supported`](https://github.com/sindresorhus/is-unicode-supported).
Once this module uses ES modules, `is-unicode-supported` should be upgraded to the latest version instead of `0.1.0`.
A follow-up question: it seems to me `windowsSymbols` be renamed to `fallbackSymbols` instead to reflect this change, what do you think?
=> Add support for Windows terminals with Unicode fonts

test.js
This simplifies the tests now that the default export and named exports are separate from each other.
This also renames some tests.
=> Simplify tests

index.js
This is a small clarification of a function used by `replaceSymbols()` since that function is only called when `shouldUseMain` is `false`.
=> Clarify `replaceSymbols()`

index.d.ts, index.js, index.test-d.ts, package.json, readme.md, test.js
This library now supports some Windows terminals providing they can display Unicode symbols.
This PR replaces all references to "Windows" to "fallback", "non-Unicode" or "older terminals" instead. This includes the named export `windowsSymbols` renamed to `fallbackSymbols`.
It also replaces "OS" by "terminal".
=> Replace references about Windows

.github/workflows/main.yml, package.json
This drops support for Node 12 (breaking change) since it is not maintained anymore.
This also adds CI tests for Node 18, and upgrade some GitHub actions.
=> Drop support for Node 12

index.js, readme.md, test.js
=> Update cross character

.github/workflows/main.yml, index.js, package.json
This drops support for Node 14 and 16, since those are not officially supported anymore.
=> Drop support for Node 14 and 16

index.js, test.js
The current intent of the `circleQuestionMark` and `questionMarkPrefix` symbols is to be displayed as circled question marks.
Unlike other symbols, this has an additional problem: this is not displayed correctly on some Linux distributions (like Ubuntu) but is displayed correctly on macOS.
The current logic has several problems. First, the condition `platform === 'linux'` should be inverted, since it currently shows the circled question mark _only_ on Linux, instead of _not_ on Linux.
https://github.com/sindresorhus/figures/blob/32fb0961ea1038182730c9ad387d6f887d4d20a5/index.js#L203-L214
Second, it leads `replaceSymbols()` to replace any normal question mark `?` to `(?)`. That's because `replaceSymbols()` was designed to replace symbols that are easily recognized as "graphical/UI" …
=> Fix `circleQuestionMark` and `questionMarkPrefix` on Linux

index.d.ts, index.test-d.ts, readme.md
The non-fallback tick symbol used in the documentation is different from the one used in the source code and tests.
- In the documentation: `U+2714` (tick) + `U+FE0E` (variation selector 15)
- In the source code and tests: `U+2714` (tick)
This fixes the documentation to match the source code.
This was previously mentioned in https://github.com/sindresorhus/figures/issues/5. This was fixed by 5ad2433c41fe7de2d0d92abd488430aabe05952f (10 years ago) but only in the source code and tests, not the `readme.md`.
=> Fix tick symbol in documentation

index.d.ts, index.js, index.test-d.ts, readme.md, test.js
=> Add `useFallback` option

.github/workflows/main.yml
This runs the CI tests on Node 22.
This also adds macOS to the CI.
=> Run CI tests on Node 22
